---

all:
  children:
    vagrant:
      hosts:
        gamesight_vagrant_app:
          ansible_host: 192.168.33.11 
          ansible_user: vagrant
          ansible_private_key_file: ~/.vagrant.d/insecure_private_key 
          ansible_ssh_common_args: '-o IdentitiesOnly=yes'

        gamesight_vagrant_db:
          ansible_host: 192.168.33.11
          ansible_user: vagrant
          ansible_private_key_file: ~/.vagrant.d/insecure_private_key 
          ansible_ssh_common_args: '-o IdentitiesOnly=yes'

        gamesight_vagrant_front:
          ansible_host: 192.168.33.11
          ansible_user: vagrant
          ansible_private_key_file: ~/.vagrant.d/insecure_private_key 
          ansible_ssh_common_args: '-o IdentitiesOnly=yes'
