---

- include: users.yml
- include: packages.yml

- name: Create base directory
  file:
    path: "{{ base_dir }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    state: directory

- name: Set permanent env variables
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  with_items:
    - "DJANGO_SETTINGS_MODULE={{ django_settings_module }}"
