---

- include: users.yml
- include: packages.yml

- name: Create base directory
  file:
    path: "{{ base_dir }}"
    owner: "{{ project_name }}"
    group: staff
    state: directory

- name: Set permanent env variables
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  with_items:
    - "DJANGO_SETTINGS_MODULE=gamesight.settings.production"
