---

- name: Make staff group for our staff users
  group:
    name: staff
    state: present

- name: Add staff users
  user:
    name: "{{ item.name }}"
    group: "{{ deploy_group }}"
    createhome: yes
    state: "{{ item.state | default('present') }}"
    shell: "/bin/bash"
  with_items: "{{ staff_ssh_users }}"

- name: Add staff keys to users
  authorized_key:
    user: "{{ item.name }}" 
    state: present
    key: "{{ item.ssh_key }}"
  with_items: "{{ staff_ssh_users }}"

- name: Grant our staff group sudo access
  lineinfile:
    line: "%staff ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers"
    mode: 0440
